import { copyFile, mkdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import type { InstallResult } from "../types/commands.js";
import { ErrorCode, type Result } from "../types/result.js";
import { toUnknownResult } from "../utils/errors.js";

const SKILL_NAMES = ["cache-ctrl-external", "cache-ctrl-local", "cache-ctrl-caller"] as const;

export function resolveOpenCodeConfigDir(overrideDir?: string): string {
  if (overrideDir !== undefined) {
    return overrideDir;
  }

  if (process.platform === "win32") {
    const appData = process.env.APPDATA ?? path.join(os.homedir(), "AppData", "Roaming");
    return path.join(appData, "opencode");
  }

  const xdgConfigHome = process.env.XDG_CONFIG_HOME ?? path.join(os.homedir(), ".config");
  return path.join(xdgConfigHome, "opencode");
}

export function buildToolWrapperContent(packageRoot: string): string {
  const normalizedPackageRoot = packageRoot.replace(/\\/g, "/");

  return [
    "// Auto-generated by cache-ctrl install — do not edit manually",
    "// Re-run 'cache-ctrl install' after 'npm update -g @thecat69/cache-ctrl'",
    `export * from \"${normalizedPackageRoot}/cache_ctrl.ts\";`,
  ].join("\n");
}

export async function installOpenCodeIntegration(configDir: string, packageRoot: string): Promise<Result<InstallResult>> {
  try {
    const toolDir = path.join(configDir, "tools");
    const toolPath = path.join(toolDir, "cache_ctrl.ts");

    await mkdir(toolDir, { recursive: true, mode: 0o755 });
    await writeFile(toolPath, buildToolWrapperContent(packageRoot), { encoding: "utf-8", mode: 0o644 });

    const skillPaths: string[] = [];

    for (const skillName of SKILL_NAMES) {
      const targetSkillDir = path.join(configDir, "skills", skillName);
      const sourceSkillPath = path.join(packageRoot, "skills", skillName, "SKILL.md");
      const targetSkillPath = path.join(targetSkillDir, "SKILL.md");

      await mkdir(targetSkillDir, { recursive: true, mode: 0o755 });
      await copyFile(sourceSkillPath, targetSkillPath);
      skillPaths.push(targetSkillPath);
    }

    return {
      ok: true,
      value: {
        toolPath,
        skillPaths,
        configDir,
      },
    };
  } catch (err) {
    const unknownError = toUnknownResult(err);
    return { ...unknownError, code: ErrorCode.FILE_WRITE_ERROR };
  }
}
