import { copyFile, mkdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import type { InstallResult } from "../types/commands.js";
import { ErrorCode, type Result } from "../types/result.js";
import { toUnknownResult } from "../utils/errors.js";

const SKILL_NAMES = ["cache-ctrl-external", "cache-ctrl-local", "cache-ctrl-caller"] as const;

/**
 * Resolves the OpenCode configuration directory.
 *
 * @param overrideDir - Explicit CLI override path.
 * @returns Absolute config directory path used for tool and skill installation.
 * @remarks Resolution order: explicit override → `%APPDATA%/opencode` on Windows →
 * `~/.config/opencode` on Unix-like systems.
 */
export function resolveOpenCodeConfigDir(overrideDir?: string): string {
  if (overrideDir !== undefined) {
    return path.resolve(overrideDir);
  }

  if (process.platform === "win32") {
    const appData = process.env.APPDATA ?? path.join(os.homedir(), "AppData", "Roaming");
    return path.join(appData, "opencode");
  }

  return path.join(os.homedir(), ".config", "opencode");
}

/** Builds the generated OpenCode tool wrapper file content. */
export function buildToolWrapperContent(packageRoot: string): string {
  const normalizedPackageRoot = packageRoot.replace(/\\/g, "/");

  return [
    "// Auto-generated by cache-ctrl install — do not edit manually",
    "// Re-run 'cache-ctrl install' after 'npm update -g @thecat69/cache-ctrl'",
    `export * from \"${normalizedPackageRoot}/cache_ctrl.ts\";`,
  ].join("\n");
}

/**
 * Installs or refreshes OpenCode tool + skill integration files.
 *
 * @param configDir - Target OpenCode config directory.
 * @param packageRoot - Installed package root used to resolve bundled assets.
 * @returns Written tool path and copied skill file paths.
 * @remarks Operation is idempotent: reruns overwrite the wrapper and recopy skill files
 * to align the config directory with the currently installed package version.
 */
export async function installOpenCodeIntegration(configDir: string, packageRoot: string): Promise<Result<InstallResult>> {
  try {
    const toolDir = path.join(configDir, "tools");
    const toolPath = path.join(toolDir, "cache_ctrl.ts");

    await mkdir(toolDir, { recursive: true, mode: 0o755 });
    await writeFile(toolPath, buildToolWrapperContent(packageRoot), { encoding: "utf-8", mode: 0o644 });

    const skillPaths: string[] = [];

    for (const skillName of SKILL_NAMES) {
      const targetSkillDir = path.join(configDir, "skills", skillName);
      const sourceSkillPath = path.join(packageRoot, "skills", skillName, "SKILL.md");
      const targetSkillPath = path.join(targetSkillDir, "SKILL.md");

      await mkdir(targetSkillDir, { recursive: true, mode: 0o755 });
      await copyFile(sourceSkillPath, targetSkillPath);
      skillPaths.push(targetSkillPath);
    }

    return {
      ok: true,
      value: {
        toolPath,
        skillPaths,
        configDir,
      },
    };
  } catch (err) {
    const unknownError = toUnknownResult(err);
    return { ...unknownError, code: ErrorCode.FILE_WRITE_ERROR };
  }
}
